# -*- coding: utf-8 -*-
"""python msa_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRPYvBI8sLlIdeCq13KpYW-PJUjV55jb
"""

from Bio import AlignIO

alignment = AlignIO.read("aligned.fasta", "fasta")

num_seqs = len(alignment)
num_cols = alignment.get_alignment_length()

print("\n===== MSA MATRIX =====\n")

for i, record in enumerate(alignment):
    print(f"Seq{i+1}: {' '.join(str(record.seq))}")

print("\n===== GAP ANALYSIS =====\n")

for col in range(num_cols):
    column = [record.seq[col] for record in alignment]
    gaps = column.count('-')
    gap_fraction = gaps / num_seqs

    classification = "I" if gap_fraction > 0.35 else "M"

    print(f"Column {col+1}: {column} | Gap Fraction = {gap_fraction:.2f} | {classification}")

